dependencies:
- name: mysql
  version: 0.10.1
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: terracotta
  version: 1.0.0
  repository: https://kubernetes-charts.storage.googleapis.com/
