server:
  port: 8080
#  servlet:
#    context-path: /thymeleaf
spring:
  thymeleaf:
    cache: false
#    mode: HTML
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#    prefix: classpath:/templates
  messages:
    basename: i18n.login
  datasource:
#    url: jdbc:mysql://localhost:3306/read_data?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

welcome:
  message: Hsiao

