spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_learn?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    initialize: true
    driver-class-name: com.mysql.cj.jdbc.Driver # com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect